### ISSUE TITLE
How to run inference using pretrained model on one image

### ISSUE THREAD

**Issue by vankhoa21991** [cad0p/maskrcnn-modanet#17]
Hello,

I read the instruction but I'm not sure how I can run the pretrained model resnet50_modanet on an image.

Thanks for your help.

**Comment by AndyHuang97** [comment]
Run the command ```!maskrcnn-modanet processimage save image``` to view the possible options (e.g. ```-p``` for a path of the image, ```-u``` for a URL of the image)

**Comment by nadia886** [comment]
> Run the command `!maskrcnn-modanet processimage save image` to view the possible options (e.g. `-p` for a path of the image, `-u` for a URL of the image)
---
!maskrcnn-modanet processimage save image \
    -p "/content/drive/MyDrive/Please Picks Collection/Cherie Edition/DSC01006.JPG" \
    -mt default \
    --save-path "/content/main/results/processedimages"

Hi, i'm trying to run the pretrained model using the command you gave but it keeps giving this error, do you mind helping me?

2024-11-25 03:01:39.324553: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-11-25 03:01:39.350057: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-11-25 03:01:39.357549: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-11-25 03:01:39.375313: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-11-25 03:01:40.770573: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Traceback (most recent call last):
  File "/usr/local/bin/maskrcnn-modanet", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/maskrcnn_modanet/cli/main.py", line 294, in image
    model, labels_to_names = processimages.loadModel(model_type=model_type, model_path=model_path)
  File "/usr/local/lib/python3.10/dist-packages/maskrcnn_modanet/processimages.py", line 28, in loadModel
    keras.backend.tensorflow_backend.set_session(get_session())
AttributeError: module 'keras.api.backend' has no attribute 'tensorflow_backend'

Thanks!

**Comment by cad0p** [comment]
You might need to downgrade keras version
